### ISSUE TITLE
feature matching

### ISSUE THREAD

**Issue by under-score** [alemart/speedy-vision#35]
great to have now also LSH/ KNN feature matching.

Unfortunately - there are null matches also in the online demo https://alemart.github.io/speedy-vision/demos/feature-matching.html

**Comment by under-score** [comment]
Yes - see the screenshot of the demo - no error in the console, but always 0 matches.

![Bildschirmfoto 2022-06-01 um 15 29 43](https://user-images.githubusercontent.com/2796454/171416747-9fa5ac89-c028-47aa-b835-091afecc3c07.jpg)

**Comment by under-score** [comment]
Found that issue on Chrome, Firefox & Safari but it works now magically, thank you.

**Comment by alemart** [comment]
If the demo didn't work yesterday but is working now, the issue was probably related to an old version of the library being cached by the browser.

When you mention that keypoint.matches[0].index is evaluated to -1, are you talking about the demo as is or do you have a different code? Have you inspected the value?

**Comment by under-score** [comment]
sorry for delay - just tried it again - it is not a cache issue on the old machine.

I was talking about the demo, and yes, the value is  always -1 also in the console.

**Comment by alemart** [comment]
Thank you for your reply.

I just submitted a slight change to a shader. Please let me know if you see any match at all (clear the cache first).

In addition, please try the demo in an operating system other than macOS if possible.

**Comment by under-score** [comment]
no issue with other machines and other OS's while the error still persists on the machine described above.

**Comment by alemart** [comment]
Unfortunately I'm unable to reproduce the issue in my machines.

If no matches are found, but the demo doesn't crash, then we have an indication that some shader in the pipeline isn't providing the expected output. Since this issue is happening on that specific machine, but not on the others, then there is the possibility of a bug in the video drivers - but I can't say for sure.

A deeper inspection of the output of the shaders in that specific machine could reveal the spot of failure and a possible workaround. However, I'm unable to do it by myself because my machines do not exhibit that failure.
