### ISSUE TITLE
Scaled images + poor results : questions

### ISSUE THREAD

**Issue by fxi** [alemart/speedy-vision#40]
Hi

Just trying out this package, no prior CV background : sorry for the noob question. 

I'm trying to create a tool to align automatically a set of images. Side project, just out of curiosity.

I've looked at your demos and just replaced your images in the `feature-matching` with my own. Poor results.

In the demo source code, it's written `ORB is NOT scale-invariant`.

As my images have different scales, does this mean that it will not work or I'm missing something ?

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/1196833/187432510-2bfc2dfc-8701-4e47-9351-e874cca5314a.png">

Final result, after a manual alignement : 

https://twitter.com/frdmsr/status/1558104339398402048?s=20&t=08JXrKAN-SFqvkZwcDtovg

Thanks !

**Comment by alemart** [comment]
Hi @fxi ,

> I've looked at your demos and just replaced your images in the feature-matching with my own. Poor results.
> 
> In the demo source code, it's written ORB is NOT scale-invariant.
> 
> As my images have different scales, does this mean that it will not work or I'm missing something ?

You are correct. You are getting poor results because ORB is not scale-invariant.

When you use ORB in a pipeline, you are computing a binary string for each keypoint. These binary strings are called feature descriptors. The feature matcher will then take these binary strings and match them.

Different feature descriptors have different characteristics. ORB is fast to compute, robust when it comes to rotations and it can handle a little bit of distortion. It's not robust when it comes to transformations in scale. This means that if you take an image and rotate it (and even distort it a little bit), you will end up with similar binary strings (meaning that you can match the keypoints). On the other hand, you will get dissimilar strings if you change the scale too much (you will get poor results).

In the case you have presented, it's advisable to transform the images so that they are approximately in the same scale. Alternatively, use a different feature descriptor. Example: BRISK is another binary descriptor that accounts for differences in scale. It's not as fast as ORB, but it's still fast. I currently don't implement it in this library. However, it's available in OpenCV. If real-time computer vision in a web browser is not a requirement for you, that should suffice.

**Comment by fxi** [comment]
Thanks !
The scale is what I'm trying to find. Scale and x, y position of image B in image A.
It should run in the browser, but not 60fps.
I close this and look at an alternative path.
`speedy-vision` is very interesting, though, so, thanks again :)
